# Generated by Django 3.0.4 on 2020-04-05 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athlete_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OH', 'On hold'), ('UE', 'Under evaluation'), ('AP', 'Apt'), ('IN', 'Inapt'), ('ME', 'Member'), ('DO', 'Dropout')], default='OH', max_length=2)),
                ('joining_date', models.DateField(blank=True, default=None)),
                ('termination_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AthleteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CON', 'Convited'), ('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('MON', 'Monitor'), ('COA', 'Coach'), ('COO', 'Coordinator')], default='BEG', max_length=3)),
                ('max_casual_leave', models.IntegerField()),
                ('max_compensation_leave', models.IntegerField()),
                ('max_earned_leave', models.IntegerField()),
                ('max_half_pay_leave', models.IntegerField()),
                ('max_leave_with_allowance', models.IntegerField()),
                ('max_duty_leave', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='time_in',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='time_out',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AB', 'Absent'), ('PR', 'Present'), ('EX', 'Excused'), ('CO', 'Compensation')], default='AB', max_length=2)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Appointment')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Athlete')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.AthleteCategory'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Team'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
