# Generated by Django 3.0.4 on 2020-04-05 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200404_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Team'),
        ),
    ]
