# Generated by Django 3.0.4 on 2020-04-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20200404_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AthleteCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'AthleteCategories'},
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('athlete', 'appointment')},
        ),
    ]
